//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_Analytics_AnalyticExtracts_View class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_Analytics_AnalyticExtracts_View {
    
    /// <summary>
    /// ASPxMenu1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxMenu.ASPxMenu ASPxMenu1;
    
    /// <summary>
    /// АналитическаяТаблица control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid АналитическаяТаблица;
    
    /// <summary>
    /// ASPxPivotGridExporter_1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.XtraPivotGrid.Web.ASPxPivotGridExporter ASPxPivotGridExporter_1;
}
