//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_Analytics_AnalyticExtracts_Setup class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_Analytics_AnalyticExtracts_Setup {
    
    /// <summary>
    /// RadAjaxManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadAjaxManager RadAjaxManager1;
    
    /// <summary>
    /// Ќадпись_аналитическа€¬ыборка control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.Ќадпись Ќадпись_аналитическа€¬ыборка;
    
    /// <summary>
    /// ¬ыпадающий—писок_отчетныеѕериоды control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.¬ыпадающий—писок ¬ыпадающий—писок_отчетныеѕериоды;
    
    /// <summary>
    /// ‘лажок_показать¬се control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.‘лажок ‘лажок_показать¬се;
    
    /// <summary>
    /// Ќадпись_предыдуща€—борка control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.Ќадпись Ќадпись_предыдуща€—борка;
    
    /// <summary>
    ///  нопка_посмотретьѕредыдущую—борку control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_посмотретьѕредыдущую—борку;
    
    /// <summary>
    ///  нопка_собрать control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_собрать;
    
    /// <summary>
    ///  нопка_отмена control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_отмена;
}
