//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_SdachaOtchetnosti_TekuschieOtchetnieFormi_TekuschieOtchetnieFormi_View class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_SdachaOtchetnosti_TekuschieOtchetnieFormi_TekuschieOtchetnieFormi_View {
    
    /// <summary>
    /// RadMenu_main control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenu RadMenu_main;
    
    /// <summary>
    /// RadMenuItem1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem1;
    
    /// <summary>
    /// RadMenuItem2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem2;
    
    /// <summary>
    /// RadMenu_√лавное control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenu RadMenu_√лавное;
    
    /// <summary>
    /// RadMenuItem_функции control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_функции;
    
    /// <summary>
    /// RadMenuItem_проверить¬нутриф control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_проверить¬нутриф;
    
    /// <summary>
    /// RadMenuItem_проверитьћежформ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_проверитьћежформ;
    
    /// <summary>
    /// RadMenuItem_сводна€ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_сводна€;
    
    /// <summary>
    /// RadMenuItem_собрать—водную control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_собрать—водную;
    
    /// <summary>
    /// RadMenuItem_јрхивƒанных control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_јрхивƒанных;
    
    /// <summary>
    /// RadMenuItem_»мпортƒанных control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_»мпортƒанных;
    
    /// <summary>
    /// RadMenuItem_Ёкспортƒанных control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_Ёкспортƒанных;
    
    /// <summary>
    /// RadMenuItem_¬осстановлениеƒанных control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_¬осстановлениеƒанных;
    
    /// <summary>
    /// RadMenuItem_печатные‘ормы control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_печатные‘ормы;
    
    /// <summary>
    /// RadMenuItem_ќбработки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem_ќбработки;
    
    /// <summary>
    /// вебЁкранна€‘орма control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.—воды.¬ебЅраузерќтчетных‘орм.¬ебЁкранна€‘орма вебЁкранна€‘орма;
    
    /// <summary>
    ///  нопка_автоблоки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_автоблоки;
    
    /// <summary>
    /// TimerPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadAjaxPanel TimerPanel;
    
    /// <summary>
    /// RadAjaxTimer_AutoSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadAjaxTimer RadAjaxTimer_AutoSave;
    
    /// <summary>
    /// Panel_AutoSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Panel_AutoSave;
    
    /// <summary>
    ///  нопка_Save control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_Save;
    
    /// <summary>
    ///  нопка_ќ  control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќ ;
    
    /// <summary>
    ///  нопка_ќтмена control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќтмена;
}
