//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_SdachaOtchetnosti_TekuschieOtchetnieFormi_TekuschieOtchetnieFormi_List class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_SdachaOtchetnosti_TekuschieOtchetnieFormi_TekuschieOtchetnieFormi_List {
    
    /// <summary>
    /// RadAjaxManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadAjaxManager RadAjaxManager1;
    
    /// <summary>
    /// AjaxLoadingPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.AjaxLoadingPanel AjaxLoadingPanel1;
    
    /// <summary>
    /// Image1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image Image1;
    
    /// <summary>
    /// RadSplitter1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadSplitter RadSplitter1;
    
    /// <summary>
    /// RadPane1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadPane RadPane1;
    
    /// <summary>
    /// ¬ыпадающий—писок_отчетныеѕериоды control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.¬ыпадающий—писок ¬ыпадающий—писок_отчетныеѕериоды;
    
    /// <summary>
    /// ƒерево_Ёлементов÷епочки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadTreeView ƒерево_Ёлементов÷епочки;
    
    /// <summary>
    /// RadSplitBar1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadSplitBar RadSplitBar1;
    
    /// <summary>
    /// RadPane2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadPane RadPane2;
    
    /// <summary>
    /// “аблица_элементы control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.“аблица “аблица_элементы;
    
    /// <summary>
    /// RadMenu1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenu RadMenu1;
    
    /// <summary>
    /// ѕодменю_внутр”в€зки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_внутр”в€зки;
    
    /// <summary>
    /// ѕунктћеню_внутр”в€зки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_внутр”в€зки;
    
    /// <summary>
    /// ѕунктћеню_внутр–езультаты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_внутр–езультаты;
    
    /// <summary>
    /// ѕодменю_меж”в€зки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_меж”в€зки;
    
    /// <summary>
    /// ѕунктћеню_межформ”в€зки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_межформ”в€зки;
    
    /// <summary>
    /// ѕунктћеню_межформ–езультаты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_межформ–езультаты;
    
    /// <summary>
    /// ѕунктћеню_ѕоказать—псок”в€зок control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_ѕоказать—псок”в€зок;
    
    /// <summary>
    /// ѕунктћеню_истори€”в€зок control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_истори€”в€зок;
    
    /// <summary>
    /// ѕунктћеню_экспертиза control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_экспертиза;
    
    /// <summary>
    /// –азделитель_”в€зки control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem –азделитель_”в€зки;
    
    /// <summary>
    /// ѕодменю_состо€ние control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_состо€ние;
    
    /// <summary>
    /// ѕунктћеню_истори€»зменений control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_истори€»зменений;
    
    /// <summary>
    /// –азделитель_печатных‘орм control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem –азделитель_печатных‘орм;
    
    /// <summary>
    /// ѕодменю_ѕечать control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_ѕечать;
    
    /// <summary>
    /// –азделитель5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem –азделитель5;
    
    /// <summary>
    /// ѕодменю_Ё÷ѕ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_Ё÷ѕ;
    
    /// <summary>
    /// ѕунктћеню_подписать control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_подписать;
    
    /// <summary>
    /// ѕунктћеню_соподписать control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_соподписать;
    
    /// <summary>
    /// ѕунктћеню_удалитьѕодпись control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_удалитьѕодпись;
    
    /// <summary>
    /// ѕунктћеню_проверитьѕодпись control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_проверитьѕодпись;
    
    /// <summary>
    /// ѕунктћеню_показатьѕодпись control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_показатьѕодпись;
    
    /// <summary>
    /// –азделитель control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem –азделитель;
    
    /// <summary>
    /// ѕодменю_данные control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕодменю_данные;
    
    /// <summary>
    /// ѕунктћеню_очистить control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem ѕунктћеню_очистить;
}
