//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_SubTable_SubTable class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_SubTable_SubTable {
    
    /// <summary>
    /// RadMenu_main control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenu RadMenu_main;
    
    /// <summary>
    /// RadMenuItem1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem1;
    
    /// <summary>
    /// RadMenuItem2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Telerik.WebControls.RadMenuItem RadMenuItem2;
    
    /// <summary>
    /// Ќабор“аблиц‘ормы_субтаблица control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.—воды.¬ебЅраузерќтчетных‘орм.Ќаборƒинамических“аблиц‘ормы Ќабор“аблиц‘ормы_субтаблица;
    
    /// <summary>
    ///  нопка_ѕересчитать control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ѕересчитать;
    
    /// <summary>
    ///  нопка_ќ  control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќ ;
    
    /// <summary>
    ///  нопка_ќтмена control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќтмена;
}
