//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_Admin_LoggedUsers_List class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_Admin_LoggedUsers_List {
    
    /// <summary>
    ///  нопка_ќбновить control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќбновить;
    
    /// <summary>
    /// “аблица_–аботающиеѕользователи control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.“аблица “аблица_–аботающиеѕользователи;
    
    /// <summary>
    /// Panel_Message_Plus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Panel_Message_Plus;
    
    /// <summary>
    /// ѕоле¬вода“екста_“екст—ообщени€ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода“екста_“екст—ообщени€;
    
    /// <summary>
    /// ѕоле¬вода„исла_—рокƒействи€ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода„исла ѕоле¬вода„исла_—рокƒействи€;
    
    /// <summary>
    ///  нопка_”становить—ообщение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_”становить—ообщение;
    
    /// <summary>
    /// Panel_Message_Minus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Panel_Message_Minus;
    
    /// <summary>
    /// Ќадпись_“екущее—ообщение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Ќадпись_“екущее—ообщение;
    
    /// <summary>
    ///  нопка_”далить“екущее—ообщение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_”далить“екущее—ообщение;
}
