//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_Profile_Profile class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_Profile_Profile {
    
    /// <summary>
    /// ѕоле¬вода_Ќаименование control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода_Ќаименование;
    
    /// <summary>
    /// ѕоле¬вода_Ћогин control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода_Ћогин;
    
    /// <summary>
    /// ѕоле¬вода_—тарыйѕароль control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода_—тарыйѕароль;
    
    /// <summary>
    /// ѕоле¬вода“екста_Ќовыйѕароль control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода“екста_Ќовыйѕароль;
    
    /// <summary>
    /// ѕоле¬вода“екста_Ќовыйѕароль2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс.ѕоле¬вода“екста ѕоле¬вода“екста_Ќовыйѕароль2;
    
    /// <summary>
    ///  нопка_ќ  control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќ ;
    
    /// <summary>
    ///  нопка_ќтмена control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ѕарс.¬ебядро.»нтерфейс. нопка  нопка_ќтмена;
}
