//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_Uchrejdenue_Uchrejdenie class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_Uchrejdenue_Uchrejdenie {
    
    /// <summary>
    /// ПолеВвода_Код control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Код;
    
    /// <summary>
    /// ПолеВвода_Наименование control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Наименование;
    
    /// <summary>
    /// ПолеВвода_ПолноеНаименование control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ПолноеНаименование;
    
    /// <summary>
    /// НаборВкладок_учр control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.НаборВкладок НаборВкладок_учр;
    
    /// <summary>
    /// Вкладка_Реквизиты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Вкладка Вкладка_Реквизиты;
    
    /// <summary>
    /// Вкладка_Персоналии control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Вкладка Вкладка_Персоналии;
    
    /// <summary>
    /// Вкладка_Атрибуты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Вкладка Вкладка_Атрибуты;
    
    /// <summary>
    /// Вкладка_Местонахождение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Вкладка Вкладка_Местонахождение;
    
    /// <summary>
    /// Вкладка_Доп control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Вкладка Вкладка_Доп;
    
    /// <summary>
    /// НаборСтраниц_учр control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.НаборСтраниц НаборСтраниц_учр;
    
    /// <summary>
    /// Страница_Реквизиты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Страница Страница_Реквизиты;
    
    /// <summary>
    /// ПолеВвода_ИНН control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ИНН;
    
    /// <summary>
    /// ПолеВвода_КПП control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_КПП;
    
    /// <summary>
    /// ПолеВвода_ПФР control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ПФР;
    
    /// <summary>
    /// ПолеВвода_НомерФилиала control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_НомерФилиала;
    
    /// <summary>
    /// ПолеВвода_ОКОНХ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКОНХ;
    
    /// <summary>
    /// ПолеВвода_ОКПО control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКПО;
    
    /// <summary>
    /// ПолеВвода_ОКУД control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКУД;
    
    /// <summary>
    /// ПолеВвода_ОКАТО control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКАТО;
    
    /// <summary>
    /// ПолеВвода_ОКВЭД control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКВЭД;
    
    /// <summary>
    /// ПолеВводаОКОГУ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВводаОКОГУ;
    
    /// <summary>
    /// ПолеВвода_ОКОПФ control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКОПФ;
    
    /// <summary>
    /// ПолеВводаОКФС control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВводаОКФС;
    
    /// <summary>
    /// ПолеВвода_ОКИН control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ОКИН;
    
    /// <summary>
    /// Страница_Персоналии control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Страница Страница_Персоналии;
    
    /// <summary>
    /// ПолеВвода_Руководитель control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Руководитель;
    
    /// <summary>
    /// ПолеВвода_ГлавБух control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ГлавБух;
    
    /// <summary>
    /// ПолеВвода_РукПланЭконСлужбы control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_РукПланЭконСлужбы;
    
    /// <summary>
    /// ПолеВводаТекста_начБюджУпр control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВводаТекста_начБюджУпр;
    
    /// <summary>
    /// Страница_Атрибуты control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Страница Страница_Атрибуты;
    
    /// <summary>
    /// ПолеВвода_НаимВРодит control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_НаимВРодит;
    
    /// <summary>
    /// ПолеВвода_ПолноеНаимВРод control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ПолноеНаимВРод;
    
    /// <summary>
    /// ПолеВвода_ВидУчреждения control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ВидУчреждения;
    
    /// <summary>
    /// ПолеВвода_ТипУчреждения control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ТипУчреждения;
    
    /// <summary>
    /// ПолеВвода_КодМОВСкиф3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_КодМОВСкиф3;
    
    /// <summary>
    /// Страница_Местонахождение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Страница Страница_Местонахождение;
    
    /// <summary>
    /// ПолеВвода_Регион control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Регион;
    
    /// <summary>
    /// ПолеВвода_Территория control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Территория;
    
    /// <summary>
    /// ПолеВвода_ТипПункта control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_ТипПункта;
    
    /// <summary>
    /// ПолеВвода_НасПункт control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_НасПункт;
    
    /// <summary>
    /// ПолеВвода_Улица control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Улица;
    
    /// <summary>
    /// ПолеВвода_Строение control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Строение;
    
    /// <summary>
    /// ПолеВвода_Корпус control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.ПолеВводаТекста ПолеВвода_Корпус;
    
    /// <summary>
    /// Страница_Доп control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Страница Страница_Доп;
    
    /// <summary>
    /// table_Attr control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable table_Attr;
    
    /// <summary>
    /// Кнопка_ОК control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Кнопка Кнопка_ОК;
    
    /// <summary>
    /// Кнопка_Отмена control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Барс.ВебЯдро.Интерфейс.Кнопка Кнопка_Отмена;
}
